[package]
name = "dsp-process"
description = "Declarative processing"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[features]
std = []

[dev-dependencies]
dsp-fixedpoint.workspace = true

[lints]
workspace = true
